#!/bin/sh 
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace experiments/ground_centralized/notebooks/*.ipynb experiments/aerial_distributed/notebooks/*.ipynb experiments/notebooks_common/*.ipynb
git add experiments/ground_centralized/notebooks/*.ipynb experiments/aerial_distributed/notebooks/*.ipynb experiments/notebooks_common/*.ipynb